runtime: go114
service: default
main: ./cmd/

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  min_pending_latency: 100ms
  max_pending_latency: 300ms

env_variables:
  FIREBASE_CONFIG_FILE: 'debaterofmath-firebase-adminsdk-9dw35-7467dad781.json'
  API_KEY_NAME: 'debaterofmath-api-key'
handlers:
  - url: /static
    static_dir: static
  - url: /
    static_files: static/meow.txt
    upload: static/.*\.(txt)$
